security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Customer:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Customer
                property: customerNumber
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: customerNumber
        api:
            pattern: ^/
            stateless: true
            jwt: ~
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
