version: '3.8'

services:

  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'bilemo'
      MYSQL_ROOT_PASSWORD: 'bilemo'
      MYSQL_USER: 'bilemo'
      MYSQL_PASSWORD: 'bilemo'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'bilemo'
      MYSQL_USER: 'bilemo'
      MYSQL_PASSWORD: 'bilemo'
    networks:
      - dev

  www:
    build: ./
    container_name: www_docker-symfony
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    restart: always
    networks:
      - dev

volumes:
  db_data:

networks:
  dev:
